name: CLS003_FOMO26_Polymicrogyria_linear_probing

modality_slots: [1]

dataset:
  _target_: src.data.FOMO26Dataset
  _partial_: true
  rootdir: ${oc.env:FOMO_FINETUNING_DATA_ROOT}
  df: processed_data/CLS003_FOMO26_Polymicrogyria/participants.tsv
  n_modalities: 1
  num_classes: 2
  folds: processed_data/CLS003_FOMO26_Polymicrogyria/split_10foldsMCCV_20260724.json
  folds_cols: participant_id
  image_col: image_path
  task_type: classification
  name: CLS003_FOMO26_Polymicrogyria

probing:
  finetuning: false
  estimator_kwargs:
    devices: 1
  save_embeddings: true
  batch_size: 32
  num_workers: 4
  pin_memory: true
  results_dir: ${oc.env:PROJECT_ROOT}/outputs/results/
  task_dir: ${task.name}
  # Pre-processing transform: Resample isotropic 1mm bspline + resizing
  trainval_transform: null
  test_transform:
    _target_: src.preprocessing.forward.ForwardPreprocessing
    resample_target_spacing: 1.0
    resizing_method: resize
    target_shape: ${eval.target_shape}
    image_interpolation: bspline
    label_interpolation: nearest
    normalization_transform:
       _target_: nidl.volume.transforms.preprocessing.RobustRescaling
       out_min_max:
         _target_: builtins.tuple
         _args_:
           - [0.0, 1.0]
       percentiles:
         _target_: builtins.tuple
         _args_:
           - [0.5, 99.5]