defaults:
  - experiment: experiment_comm_neurojepa_high_res
  - encoder: vit_neurojepa_moe
  - model: comm_neurojepa
  - dataset: train_multimodal
  - _self_

model:
  enc_ckpt: null
  learning_rate: 2.5e-5
  lr_scheduler: "warmup_cosine"
  lr_scheduler_kwargs:
    warmup_epochs: 4
    warmup_start_lr: 1e-6
    min_lr: 1e-6
    interval: "step"

  max_epochs: 15
  num_nodes: 4

experiment:
  warm_start_ckpt: ???
  
hydra:
  run:
    dir: ${oc.env:PRETRAINED_CHECKPOINTS_ROOT}/comm_neurojepa_high_res/${hydra:job.override_dirname}
  output_subdir: .hydra