_target_: nidl.volume.backbones.vit3d_moe.VisionTransformer3D
img_size:
  - ${experiment.img_size}
  - ${experiment.img_size}
  - ${experiment.img_size}
patch_size: [16, 16, 16]
in_chans: ${experiment.modalities_count}
embed_dim: 768
depth: 12
num_heads: 12
mlp_ratio: 4.0
use_moe: true

moe_params:
  _target_: nidl.volume.backbones.vit3d_moe.MoEParams
  dim: 768
  n_shared_experts: 2
  n_routed_experts: 16
  n_activated_experts: 6
  moe_inter_dim: 384
  score_func: "softmax"
  route_scale: 4.0
  bias_clip: 0.3
  bias_update_rate: 1e-4
  moe_layer_indices: [1, 3, 5, 7, 9, 11]